#!/bin/bash

# fleetsie_gen_server - allocate new devices for a fleet

function usage() {
    cat <<EOF
Usage:

fleetsie_gen_server NUM FLEETNAME

- add NUM new devices to fleet FLEETNAME

fleetsie_gen_server is the server-side script called by fleetsie_gen (which runs on a user's PC).

Several databases are used:

  - Master: /home/fleetsie/fleets.sqlite - all new devices are
            allocated here, and eventually, their registration to a
            hardware device is reflected here.

  - Fleet: /home/fleetsie_FLEETNAME/fleet.sqlite - new devices are copied
           here from Master.  This DB is used by fleetsieauth when a device is
 	   being provisioned, and is the first place where the (HWID, device) pairing
 	   is made (i.e. the device is registered).

  - Provisioning: /home/fleetsie_FLEETNAME/provisioning.sqlite - a reduced version
    of the Fleet database, with only the OTP and index_in_fleet columns.  Rows
    represent allocated but unregistered devices for this fleet.  This is
    updated whenever new devices are allocated to the fleet, or when devices are
    registered.  This database is copied to the USB provisioning disk by fleetsie_gen,
    and is used by a device that is provisioning itself.

fleetsie_gen_server does these things:

- if NUM > 0, N new devices are allocated to fleet FLEETNAME (provided there are enough TCP ports remaining),
  and these are appended to the Master, Fleet, and Provisioning databases.

- regardless of NUM, update the Master database with any new registrations from the fleet database

EOF
    exit $1
}

# Set the range of TCP ports that fleetsie can assign for mapping back to device SSH server ports.
# All devices in all fleets on this server are allocated a unique port in this range.
MIN_TCP_PORT=20000
MAX_TCP_PORT=29999

# Note: the fleet server should be kept from using these ports when creating new TCP connections
# Typically, a linux box shows this:
#    $ cat /proc/sys/net/ipv4/ip_local_port_range
#    32768	60999
# which means ports in the range 20000-29999 won't be used as ephemeral ports for outgoing connections,
# so should be available for ssh to map.
# If necessary, the file /etc/sysctl.d/fleetsie can be created on the server, with this line:
#  net.ipv4.ip_local_port_range=32768 60999
# to keep the range away from 20000-29999.

NUM="$1"
if [[ ! "$NUM" =~ ^[0-9]+$ ]]; then
    usage
fi
shift
FLEETNAME="$1"
if [[ ! "$FLEETNAME" =~ ^[-_[:alnum:]]+$ ]]; then
    usage
fi

FLEETUSER="fleetsie_$FLEETNAME"
if [[ ! if id -u test 2> /dev/null; then
	# we set the shell to be a program that manages
	sudo adduser --disabled-password --gecos '""' --ingroup fleetsie --shell /home/fleetsie/fleetsie_login $FLEETUSER
