#!/bin/bash

# placeholder script - modify as you wish.  This is run on the device before
# fleetsie_provision looks for the USB provisioning disk, before
# installing any .deb files found in ./packages

