#!/bin/bash

# install - run as part of fleetsiemod when modifying a Raspberry Pi OS image
#
# This script must be run from the directory it lives in.
# It assumes the target image partitions are mounted in the directory
# given by environment variable TARGET_ROOT.  The partitions there must
# be avilable via symlinks "bootfs" and "rootfs"

BOOTFS=$TARGET_ROOT/bootfs
ROOTFS=$TARGET_ROOT/rootfs
SYSTEMD=$ROOTFS/etc/systemd/system
OPT=$ROOTFS/opt/fleetsie

FIRMWARE_ARCH=$TARGET_ROOT/firmware-stable.zip
FIRMWARE_URL=https://github.com/raspberrypi/firmware/archive/refs/heads/stable.zip

# update firmware, possibly fetching the archive first.
if [[ ! -f $FIRMWARE_ARCH ]]; then
    cat <<EOF
The file $FIRMWARE_ARCH does not exist in folder $PWD.
If you want me to download it, hit Enter.  Otherwise, hit Ctrl-C
to abort installation.
EOF
    read ignore
    curl -o $FIRMWARE_ARCH $FIRMWARE_URL
fi

unzip -j -o -d $BOOTFS $FIRMWARE_ARCH **/start*.elf **/fixup*.dat

DST=$SYSTEMD/fleetsie-provision.service
cp ./fleetsie-provision.service $DST
chown root:root $DST
ln -sf /etc/systemd/system/fleetsie-provision.service $SYSTEMD/multi-user.target.wants

mkdir -p $OPT
chown root:root $OPT
DST=$OPT/fleetsie_provision
cp ./fleetsie_provision $DST
chown root:root $DST
chmod oug+x $DST
