#!/bin/bash

# install - run as part of fleetsiemod when modifying a Raspberry Pi OS image
#
# This script must be run from the directory it lives in.
# It assumes the target image partitions are mounted in the directory
# given by environment variable TARGET_ROOT.  The partitions there must
# be avilable via symlinks "bootfs" and "rootfs"

BOOTFS=$TARGET_ROOT/bootfs
ROOTFS=$TARGET_ROOT/rootfs
SYSTEMD=$ROOTFS/etc/systemd/system

DST=$SYSTEMD/fleetsie.service
cp ./fleetsie.service $DST
chown root:root $DST
chmod oug+x $DST
ln -s /etc/systemd/system/fleetsie.service $SYSTEMD/multi-user.target.wants

DST=$ROOTFS/usr/sbin/fleetsie_provision
cp ./fleetsie_provision $DST
chmown root:root $DST
chown oug+x $DST
